version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.3-node-browsers
    - image: circleci/postgres:10-postgis
      environment:
        POSTGRES_USER: circle-ci
        POSTGRES_DB: circle_test
    working_directory: ~/repo
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/gueroverde/scrapper-test/compare/67ceed6b0a90a66f2d941a87288df9be4e2c6bd7...6e3d3b8919a54af980792f9ee9f22653889cbfbe
    - DB_CONNECTION: pgsql
    - DB_HOST: localhost
    - DB_PORT: 5432
    - DB_DATABASE: circle_test
    - DB_USERNAME: circle-ci
    - APP_ENV: testing
    - APP_DEBUG: false
    - hideDefaultLocaleInURL: true
    steps:
    - checkout
    - run:
        name: Update OS
        command: sudo apt-get update
    - run:
        name: Install libraries
        command: |
          sudo apt-get install libzip-dev libwebp-dev libjpeg-dev libpng-dev libz-dev libxpm-dev libmcrypt-dev libpq-dev
          sudo pecl channel-update pecl.php.net
          sudo pecl install zip && sudo docker-php-ext-enable zip
          sudo -E docker-php-ext-install gd
          sudo -E docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath
          sudo -E docker-php-ext-install mcrypt && sudo docker-php-ext-enable mcrypt
          sudo -E docker-php-ext-install mbstring && sudo docker-php-ext-enable mbstring
          sudo -E docker-php-ext-install exif && sudo docker-php-ext-enable exif
          sudo docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
          sudo -E docker-php-ext-install pdo pdo_pgsql pgsql && sudo docker-php-ext-enable pdo pdo_pgsql pgsql
    - run:
        name: Set APP_KEY as environment variable
        command: |
          echo 'export APP_KEY=$(php artisan key:generate --show)' >> $BASH_ENV
          source $BASH_ENV
          echo $APP_KEY
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        - v1-dependencies-
    - run: composer install -n --prefer-dist
    - save_cache:
        key: v1-dependencies-{{ checksum "composer.json" }}
        paths:
        - ./vendor
    - run:
        name: Run migrations
        command: php artisan migrate:fresh --seed --env=testing
    - restore_cache:
        keys:
        - node-v1-{{ checksum "package.json" }}
        - node-v1-
    - run: npm install
    - save_cache:
        key: node-v1-{{ checksum "package.json" }}
        paths:
        - node_modules
    - run: php artisan migrate:fresh --seed --env=testing
    - run: ./vendor/bin/phpunit
    - run: npm test
workflows:
  version: 2
  test:
    jobs:
    - build